#ifndef _HENINPUT_H_
#define _HENINPUT_H_

#include "SDL3/SDL.h"

#include "vendor/glm/glm.hpp"

namespace hen::input
{
    enum BUTTON
    {
        NONE = 0,

        DIGIT_RANGE_START = 48, // 0

		CHARACTER_RANGE_START = 65, // A

        MOUSE_BUTTON_LEFT,
		MOUSE_BUTTON_RIGHT,
		MOUSE_BUTTON_MIDDLE,

        KEYBOARD_BUTTON_UP,
		KEYBOARD_BUTTON_DOWN,
		KEYBOARD_BUTTON_LEFT,
		KEYBOARD_BUTTON_RIGHT,
		KEYBOARD_BUTTON_SPACE,
		KEYBOARD_BUTTON_RSHIFT,
		KEYBOARD_BUTTON_LSHIFT,
		KEYBOARD_BUTTON_F1,
		KEYBOARD_BUTTON_F2,
		KEYBOARD_BUTTON_F3,
		KEYBOARD_BUTTON_F4,
		KEYBOARD_BUTTON_F5,
		KEYBOARD_BUTTON_F6,
		KEYBOARD_BUTTON_F7,
		KEYBOARD_BUTTON_F8,
		KEYBOARD_BUTTON_F9,
		KEYBOARD_BUTTON_F10,
		KEYBOARD_BUTTON_F11,
		KEYBOARD_BUTTON_F12,
		KEYBOARD_BUTTON_ENTER,
		KEYBOARD_BUTTON_ESCAPE,
		KEYBOARD_BUTTON_HOME,
		KEYBOARD_BUTTON_RCONTROL,
		KEYBOARD_BUTTON_LCONTROL,
		KEYBOARD_BUTTON_DELETE,
		KEYBOARD_BUTTON_BACKSPACE,
		KEYBOARD_BUTTON_PAGEDOWN,
		KEYBOARD_BUTTON_PAGEUP,
		KEYBOARD_BUTTON_NUMPAD0,
		KEYBOARD_BUTTON_NUMPAD1,
		KEYBOARD_BUTTON_NUMPAD2,
		KEYBOARD_BUTTON_NUMPAD3,
		KEYBOARD_BUTTON_NUMPAD4,
		KEYBOARD_BUTTON_NUMPAD5,
		KEYBOARD_BUTTON_NUMPAD6,
		KEYBOARD_BUTTON_NUMPAD7,
		KEYBOARD_BUTTON_NUMPAD8,
		KEYBOARD_BUTTON_NUMPAD9,
		KEYBOARD_BUTTON_MULTIPLY,
		KEYBOARD_BUTTON_ADD,
		KEYBOARD_BUTTON_SEPARATOR,
		KEYBOARD_BUTTON_SUBTRACT,
		KEYBOARD_BUTTON_DECIMAL,
		KEYBOARD_BUTTON_DIVIDE,
		KEYBOARD_BUTTON_TAB,
		KEYBOARD_BUTTON_TILDE,
		KEYBOARD_BUTTON_INSERT,
		KEYBOARD_BUTTON_ALT,
		KEYBOARD_BUTTON_ALTGR,

        BUTTON_ENUM_SIZE
    };

    struct KeyboardState
	{
		bool Buttons[BUTTON_ENUM_SIZE] = {}; // no continuous presses
	};

    struct MouseState
	{
		glm::vec2 Pos = glm::vec2(0.0f, 0.0f);
		glm::vec2 DeltaPos = glm::vec2(0.0f, 0.0f);
		float DeltaWheel = 0;
		float Pressure = 1.0f;
		bool LMB = false;
		bool MMB = false;
		bool RMB = false;
	};

    void Update();
    void GetKeyboardState(KeyboardState* state);
    void GetMouseState(MouseState* state);

    void ProcessEvent(const SDL_Event& event);

}

#endif // !_HENINPUT_H_